### List all messages
GET http://localhost:3000/messages

### Create a message
POST http://localhost:3000/messages 
content-type: application/json

{
  "content": "hello"
}

### Get a message
GET http://localhost:3000/messages/789ww